name: run pre-commit checks
on:
  push:
    branches:
      - documentation

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/antonbabenko/pre-commit-terraform:latest
    steps:
         - name: Check out repository code
           uses: actions/checkout@v2
         - name: running pre-commit
           run: |
             docker -v $(pwd):/lint -w /lint run -a
