name: run pre-commit checks
on:
  push:
    branches:
      - documentation

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/antonbabenko/pre-commit-terraform:latest
      options: run -a
    steps:
         - name: Check out repository code
           uses: actions/checkout@v2
